// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfettiController from "./confetti_controller"
application.register("confetti", ConfettiController)

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import DirectUploadController from "./direct_upload_controller"
application.register("direct-upload", DirectUploadController)

import FadeController from "./fade_controller"
application.register("fade", FadeController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomeController from "./home_controller"
application.register("home", HomeController)

import LinkClickController from "./link_click_controller"
application.register("link-click", LinkClickController)

import LogoController from "./logo_controller"
application.register("logo", LogoController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PhoneController from "./phone_controller"
application.register("phone", PhoneController)

import YomTovToggleController from "./yom_tov_toggle_controller"
application.register("yom-tov-toggle", YomTovToggleController)
