WITH country_codes (country_name, country_code) AS (
  VALUES
    ('United States', '+1'),
    ('Argentina', '+54'),
    ('Australia', '+61'),
    ('Austria', '+43'),
    ('Belarus', '+375'),
    ('Belgium', '+32'),
    ('Belize', '+501'),
    ('Benin', '+229'),
    ('Bhutan', '+975'),
    ('Bolivia', '+591'),
    ('Brazil', '+55'),
    ('Brunei', '+673'),
    ('Canada', '+1c'),
    ('Chile', '+56'),
    ('Colombia', '+57'),
    ('Comoros', '+269'),
    ('Congo', '+242'),
    ('Costa Rica', '+506'),
    ('Croatia', '+385'),
    ('Cuba', '+53'),
    ('Cyprus', '+357'),
    ('Czech Republic', '+420'),
    ('Denmark', '+45'),
    ('Ecuador', '+593'),
    ('Egypt', '+20'),
    ('El Salvador', '+503'),
    ('Finland', '+358'),
    ('France', '+33'),
    ('Georgia', '+995'),
    ('Germany', '+49'),
    ('Greece', '+30'),
    ('Guatemala', '+502'),
    ('Haiti', '+509'),
    ('Honduras', '+504'),
    ('Hungary', '+36'),
    ('Iceland', '+354'),
    ('Iran', '+98'),
    ('Iraq', '+964'),
    ('Ireland', '+353'),
    ('Israel', '+972'),
    ('Italy', '+39'),
    ('Jamaica', '+1-876'),
    ('Japan', '+81'),
    ('Jordan', '+962'),
    ('Lebanon', '+961'),
    ('Mexico', '+52'),
    ('Monaco', '+377'),
    ('Mongolia', '+976'),
    ('Morocco', '+212'),
    ('Netherlands', '+31'),
    ('New Zealand', '+64'),
    ('Peru', '+51'),
    ('Philippines', '+63'),
    ('Poland', '+48'),
    ('Portugal', '+351'),
    ('Qatar', '+974'),
    ('Romania', '+40'),
    ('Russia', '+7'),
    ('Saudi Arabia', '+966'),
    ('Singapore', '+65'),
    ('South Africa', '+27'),
    ('Spain', '+34'),
    ('Sweden', '+46'),
    ('Switzerland', '+41'),
    ('Thailand', '+66'),
    ('Turkey', '+90'),
    ('Ukraine', '+380'),
    ('United Arab Emirates', '+971'),
    ('United Kingdom', '+44')
)
SELECT
  ads.*,
  country_codes.country_name
FROM
  ads
LEFT JOIN
  country_codes ON ads.country = country_codes.country_code;
